name: CI/CD

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'deploy'
      - name: Generate Environment Variables File for Production
        run: |
          echo "VITE_KAKAO_API_KEY=$VITE_KAKAO_API_KEY" >> .env.production
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          VITE_SERVER_IP: ${{ secrets.VITE_SERVER_IP }}
      - run: yarn install
      - run: yarn build
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
